config/routes.rb
Demo4::Application.routes.draw do
  resources :activities

  get "stucks/index"
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :priorities
  resources :stucks
  match 'team', to: 'home#team', via: :get
  match 'invitation', to: 'home#invitation', via: :get
  match 'completed/:id', to: 'priorities#completed', via: :patch, as: 'completed'
  match 'unstuck/:id', to: 'stucks#unstuck', via: :patch, as: 'unstuck'
  match 'urgency/:id', to: 'priorities#urgency', via: :patch, as: 'urgency'
  match 'blocks', to: 'stucks#blocks', via: :get
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  
  validates :content, presence: true
  validates :content, length: { in: 9..250 }
  
  belongs_to :user
  
  default_scope { order(high: :desc, created_at: :desc)}
  
  scope :active_by_user, ->(user) { where(complete: false, :user_id => user) }
  
  def toggle_urgent
    high = !self.high
  end
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  def new
    @priority = Priority.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @priority }
      format.js
    end
  end

  def index
    @priority = Priority.new
    @priorities = Priority.active_by_user(current_user)
  end
  
  def create
    @user = current_user
    @priority = @user.priorities.new(priority_params)
    if @priority.save
      track_activity @priority
      redirect_to priorities_path, notice: "new priority added"
    else
      redirect_to action: :index
    end
  end
  
  def completed
    @priority = Priority.find(params[:id])
    @priority.update_attribute :complete, true
    track_activity @priority
    @priorities = Priority.active_by_user(current_user)
    respond_to do |format|
      format.html { redirect_to(priorities_path) }
      format.js
    end
  end
  
  def urgency
    @priority = Priority.find(params[:id])
    @priority.update_attribute :high, @priority.toggle_urgent
    @priorities = Priority.active_by_user(current_user)
    respond_to do |format|
      format.html { redirect_to(priorities_path) }
      format.js
    end
  end
  
  private
    def priority_params
      params.require(:priority).permit(:content, :complete, :high)
    end
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
  def priority_display_class(highlow)
    highlow ? "prio-high-panel radius callout" : "prio-low-panel radius lower" 
  end
  
  def priority_display_link(highlow)
		highlow ? '<i class="fi-next"></i> Push' : '<i class="fi-flag"></i> Today'
  end
end

app/views/priorities/_form.html.erb
    <%= simple_form_for @priority, :html => { :class => 'form-horizontal' } do |f| %>
     <div class="row">
	    <div class="small-12 columns">
	      <%= f.input :content, :label => false, :placeholder => "Add Priority" %>
	      
	    </div>
	    <div class="small-6 columns">
		  <%= f.input_field :high, :inline_label => " Due Today" %>
		</div>
		<div class="small-6 columns">
		  <%= f.button :submit, 'Add Priority', :class => 'button tiny radius round right' %>
		</div>
	  </div>
	<% end %>

	

app/views/priorities/_priority.html.erb
<div class="<%= priority_display_class(priority.high) %> clearfix">
  <div class="row">
	<div class="small-12 columns ">
      <p><%= priority.content %></p>
    </div>
  </div>
  <div class="action-bar-<%= priority.high? ? 'high' : 'low' %>-panel right">
    <ul class="inline-list"> 
      <li><%= link_to completed_path(priority), :method => :patch, remote: true  do %>
	        <i class="fi-trophy"></i> Complete
	      <% end %>
	  </li>
	  <li><%= link_to root_path do %>
	        <i class="fi-comment-quotes"></i> Comment
	      <% end %>
	  </li> 
	  <li> <%= link_to urgency_path(priority), :method => :patch, remote: true do %>
			  <%= raw(priority_display_link(priority.high)) %>
			 <% end %>
	  </li>
      <li><%= link_to root_path do %>
	        <i class="fi-x"></i> Delete
	      <% end %>
	  </li> 
    </ul>
  </div>
</div>

app/views/priorities/completed.js.erb
$('#priorities').html('<%= escape_javascript(render(@priorities)) %>');

app/views/priorities/index.html.erb
<ul class="button-group">
  <li><a href="#" class="button">Priorities</a></li>
  <li><%= link_to "Blocks", blocks_path, :class => "button secondary" %></li>
  <li><%= link_to "Stucks", stucks_path, :class => "button secondary" %></li>
</ul> 
  <div class="content small-12 medium-6 large-6" id="panel2-1"> 
    <%= render 'form' %>
    <div id="priorities">
    <%= render @priorities %>
    </div>
  </div> 

app/views/priorities/new.html.erb
<h1>Priorities#new</h1>
<p>Find me in app/views/priorities/new.html.erb</p>

app/views/priorities/urgency.js.erb
$('#priorities').html('<%= escape_javascript(render(@priorities)) %>');