config/routes.rb
Demo4::Application.routes.draw do
  resources :activities

  get "stucks/index"
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :priorities
  resources :stucks
  match 'team', to: 'home#team', via: :get
  match 'invitation', to: 'home#invitation', via: :get
  match 'completed/:id', to: 'priorities#completed', via: :patch, as: 'completed'
  match 'unstuck/:id', to: 'stucks#unstuck', via: :patch, as: 'unstuck'
  match 'urgency/:id', to: 'priorities#urgency', via: :patch, as: 'urgency'
  match 'blocks', to: 'stucks#blocks', via: :get
end

app/models/stuck.rb
class Stuck < ActiveRecord::Base
  
  validates :content, presence: true
  validates :content, length: { in: 9..250 }
  
  belongs_to :user
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  
  default_scope { order(created_at: :desc)}
  
  scope :active_by_user, ->(user) { where(complete: false, :user_id => user) }
  scope :active_blocks, ->(user) { where(complete: false, :owner_id => user) }
  
end

app/controllers/stucks_controller.rb
class StucksController < ApplicationController
  def index
    @stuck = Stuck.new
    @stucks = Stuck.active_by_user(current_user)
  end
  
  def create
    @user = current_user
    @stuck = @user.stucks.new(stuck_params)
    if @stuck.save
      track_activity @stuck
      redirect_to stucks_path, notice: "new stuck added"
    else
      render :root_path
    end
  end
  
  def update
    @stuck = Stuck.find(params[:id])
    @stuck.update_attributes(stuck_params)
    respond_to do |format|
      format.html { redirect_to(current_user.id == @stuck.owner_id ? blocks_path : stucks_path) }
      format.js
    end
  end
  
  def completed
    @stuck = Stuck.find(params[:id])
    @stuck.update_attribute :complete, true
    @stucks = Stuck.active_by_user(current_user)
    respond_to do |format|
      format.html { redirect_to(stucks_path) }
      format.js
    end
  end
  
  def unstuck
    @stuck = Stuck.find(params[:id])
    @stuck.update_attribute :complete, true
    @stucks = Stuck.active_blocks(current_user)
    respond_to do |format|
      format.html { redirect_to(blocks_path) }
      format.js
    end
  end
  
  def blocks
    @stucks = Stuck.active_blocks(current_user)
    respond_to do |format|
      format.html 
      format.js
    end
  end
  
  private
    def stuck_params
      params.require(:stuck).permit(:content, :complete, :owner_id)
    end
end

app/helpers/stucks_helper.rb
module StucksHelper
  def stuck_display_content(stuck)
    @display_content = nil 
    if stuck.owner_id
      @user = User.find(stuck.owner_id)
      if @user
        @display_content = raw( '<span class="assigned">' + 
        @user.name + 
        '</span>' + 
        " owns the stuck:  <br />  " + 
        stuck.content)
      end
    end
      @display_content ||= raw('<span class="assigned alert">' + "currently unassigned: </span><br />" + stuck.content)   
  end
  
  def block_display_content(block)
    @display_content = nil 
      @user = User.find(block.user_id)
      if @user
        @display_content = raw( '<span class="assigned">' + 
        @user.name + 
        '</span>' + 
        " assigned you their stuck:  <br />  " + 
        block.content)
      end
      @display_content ||= raw('<span class="assigned alert">' + "orphaned stuck: </span><br />" + block.content)   
  end
end

app/views/stucks/_block.html.erb
<div class="content"> 
	<div class="prio-high-panel callout radius clearfix">
	  	<img class="radius profile"src="images/default_profile.jpg">
		       <span class="update-text"><%= block_display_content(block) %></span>
		<div class="row right">
	        <ul class="inline-list action-bar-high-panel">  
		      <li><%= link_to unstuck_path(block), :method => :patch, remote: true  do %>
			        <i class="fi-trophy"></i> Unstuck
			      <% end %>
			  </li>
			  <li><%= link_to root_path do %>
			        <i class="fi-comment-quotes"></i> Comment
			      <% end %>
			  </li>
			  <li><%= link_to root_path, :data => {:'reveal-id' => "myModal"} do %>
			        <i class="fi-torso"></i> Reassign
			      <% end %>
			  </li>
		    </ul>
		  </div>
	</div> 
  </div>
<div id="myModal" class="reveal-modal" data-reveal> 
  <div class="row">
    <div class="large-12 columns">
	<%= simple_form_for(block) do |f| %>
      <img class="radius profile"src="images/default_profile.jpg"><span class="profile-select-text">
      <%= User.find_by_id(block.owner_id).try(:name) %></span>
      <%= f.association :owner, :label => false %>
      <%= f.button :submit, :class => 'button tiny radius round right' %>
    <% end %>
    </div>
  </div> 
	<a class="close-reveal-modal">&#215;</a> 
</div>

app/views/stucks/_form.html.erb
		<%= simple_form_for @stuck, :html => { :class => 'form-horizontal' } do |f| %>
		 <div class="row">
		    <div class="small-12 columns">
		      <%= f.input :content, :label => false, :placeholder => "Add Stuck" %>
		    </div>
			<div class="small-6 columns">
			  <%= f.button :submit, :class => 'button tiny radius round right' %>
			</div>
		  </div>
		<% end %>

app/views/stucks/_stuck.html.erb
<div class="prio-high-panel callout radius clearfix">
   <a href="#" data-reveal-id="myModal<%= stuck.id%>"><img class="radius profile"src="images/default_profile.jpg"></a>
     <span class="update-text"><%= stuck_display_content(stuck) %></span>
   	<div class="row right">
        <ul class="inline-list action-bar-high-panel">  
	      <li><%= link_to root_path do %>
		        <i class="fi-comment-quotes"></i> Comment
		      <% end %>
		  </li>
		  <li><%= link_to root_path do %>
		        <i class="fi-x"></i> Delete
		      <% end %>
		  </li>
	    </ul>
	</div>
</div>
<div id="myModal<%= stuck.id%>" class="reveal-modal" data-reveal> 
  <div class="row">
    <div class="large-12 columns">
	<%= simple_form_for(stuck) do |f| %>
      <img class="radius profile"src="images/default_profile.jpg"><span class="profile-select-text">
      <%= User.find_by_id(stuck.owner_id).try(:name) %></span>
      <%= f.association :owner, :label => false %>
      <%= f.button :submit, :class => 'button tiny radius round right' %>
    <% end %>
    </div>
  </div> 
	<a class="close-reveal-modal">&#215;</a> 
</div>

app/views/stucks/blocks.html.erb
<ul class="button-group">
  <li><%= link_to "Priorities", priorities_path, :class => "button secondary" %></li>
  <li><a href="#" class="button">Blocks</a></li>
  <li><%= link_to "Stucks", stucks_path, :class => "button secondary" %></li>
</ul>
<div id="blocks" class="large-6 medium-8 small-12">
   <%= render partial: 'block', collection: @stucks %>
</div>

app/views/stucks/index.html.erb
<ul class="button-group">
  <li><%= link_to "Priorities", priorities_path, :class => "button secondary" %></li>
  <li><%= link_to "Blocks", blocks_path, :class => " secondary button" %></li>
  <li><%= link_to "Stucks", stucks_path, :class => "button" %></li>
</ul>
  <div class="content small-12 medium-8 large-6" id="panel2-3"> 
    <%= render 'form' %>
    <div id="stucks">
    <%= render @stucks %>
    </div> 
  </div> 

app/views/stucks/unstuck.js.erb
$('#blocks').html("<%= escape_javascript(render :partial => 'block', :collection => @stucks) %>");