config/routes.rb
Demo4::Application.routes.draw do
  resources :activities

  get "stucks/index"
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :priorities
  resources :stucks
  match 'team', to: 'home#team', via: :get
  match 'invitation', to: 'home#invitation', via: :get
  match 'completed/:id', to: 'priorities#completed', via: :patch, as: 'completed'
  match 'unstuck/:id', to: 'stucks#unstuck', via: :patch, as: 'unstuck'
  match 'urgency/:id', to: 'priorities#urgency', via: :patch, as: 'urgency'
  match 'blocks', to: 'stucks#blocks', via: :get
end

app/views/layouts/_left_canvas.html.erb
<% if user_signed_in? %>
<ul class="off-canvas-list"> 
  <li><label>Aldershot</label></li>
  <li><a href="#">Personal</a></li>
  <li><a href="#">Family</a></li>
  <li><a href="#">Career</a></li>
  <li><a href="#">Community</a></li>
</ul>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_mobile.html.erb
<div class="large-4 columns">
	<div class="section-container auto" data-section>
	  <section class="active">
	    <div class="title" data-section-title><a href="#panel1">3<br/> Priorities</a></div>
	    <div class="content" data-section-content>
	      <p><input type="text" placeholder="New Priority"></p>
	      <div class="section-container accordion" data-section="accordion">
		  <section>
		    <p class="title" data-section-title><a href="#">Priority 1</a></p>
		    <div class="content" data-section-content>
		      <p>
			    <a href="#" class="button tiny round alert">Cancel</a>
			    <a href="#" class="button tiny round success">
				  <i class="gen-icon-star"></i>
				</a>
			    <a href="#" class="button tiny round success">
				  <i class="gen-icon-star"></i>
				  <i class="gen-icon-star"></i>
				</a>
			    <a href="#" class="button tiny round success">
				  <i class="gen-icon-star"></i>
				  <i class="gen-icon-star"></i>
				  <i class="gen-icon-star"></i>
				</a>
			  </p>
		    </div>
		  </section>
		  <section>
		    <p class="title" data-section-title><a href="#">Priority 2</a></p>
		    <div class="content" data-section-content>
		      <p>Content of section 2.</p>
		    </div>
		  </section>
		</div>
	    </div>
	  </section>
	  <section>
	    <div class="title" data-section-title><a href="#panel2">4<br/> Stucks</a></div>
	    <div class="content" data-section-content>
	      <p><input type="text" placeholder="New Stuck"></p>
	      <div class="section-container accordion" data-section="accordion">
		  <section>
		    <p class="title" data-section-title><a href="#">Stuck 1</a></p>
		    <div class="content" data-section-content>
		      <p>Content of section 1.</p>
		    </div>
		  </section>
		  <section>
		    <p class="title" data-section-title><a href="#">Stuck 2</a></p>
		    <div class="content" data-section-content>
		      <p>Content of section 2.</p>
		    </div>
		  </section>
		</div>
	    </div>
	  </section>
	  <section>
	    <div class="title" data-section-title><a href="#panel2">2<br/> Blocking</a></div>
	    <div class="content" data-section-content>
	      	<div class="section-container accordion" data-section="accordion">
			  <section>
			    <p class="title" data-section-title><a href="#">John Doe wants you to.... </a></p>
			    <div class="content" data-section-content>
			      <p><input type="text" placeholder="Update John Doe">.</p>
			    </div>
			  </section>
			  <section>
			    <p class="title" data-section-title><a href="#">Jane Doe wants you to ....</a></p>
			    <div class="content" data-section-content>
			      <p><input type="text" placeholder="Update Jane Doe"></p>
			    </div>
			  </section>
			</div>
	    </div>
	  </section>
	</div>
</div>

app/views/layouts/_navigation.html.erb
   <ul class="top-bar-button inline-list">
	  <li><%= link_to root_path do %>
	        <i class="fi-home style4"></i>
	      <% end %>
	  </li>
	  <% if user_signed_in? %> 
	  <li><%= link_to priorities_path do %>
	        <i class="fi-checkbox style4"></i>
	      <% end %>
	  </li>
	  <li><%= link_to team_path do %>
	        <i class="fi-torsos-all style4"></i>
	      <% end %>
	  </li>
	  <li><%= link_to invitation_path do %>
	        <i class="fi-link style4"></i>
	      <% end %>
	  </li>
	  <% end %>
	</ul>
	

app/views/layouts/_right_canvas.html.erb
<% if user_signed_in? %>
<ul class="off-canvas-list">
	<li><label>Account</label></li>
    <li><%= link_to "Edit Profile", edit_user_registration_path(current_user) %></li>
	<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
	<li><label>Teams</label></li>
	<li><a href="#">Manage Teams</a></li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Aldershot" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="off-canvas-wrap">
	  <div class="inner-wrap">
		<nav class="tab-bar has-form has-dropdown" data-topbar> 
		  <section class="left-small">
		    <a class="left-off-canvas-toggle menu-icon" ><span></span></a>
		  </section>
		  <section class="middle tab-bar-section">
		   <%= render 'layouts/navigation' %>
		  </section>
		  <section class="right-small">
		    <a class="right-off-canvas-toggle menu-icon" ><span></span></a>
		  </section>
		</nav> 
		<aside class="left-off-canvas-menu"> 
          <%= render 'layouts/left_canvas' %>
		</aside> 
		<aside class="right-off-canvas-menu"> 
          <%= render 'layouts/right_canvas' %>
		</aside> 
		<section class="main-section">
		  <div class="row">
            <div class="small-11 small-centered columns">
	          &nbsp;
	          <header>
		        <%= render 'layouts/messages' %>
		      </header>
	        </div> 
			<div class="small-11 small-centered columns"><%= yield %></div> 
	      </div>
		</section> 
		  <a class="exit-off-canvas"></a> 
	  </div>
	</div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application_bkup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Demo4" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Demo4" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
	   <div class="row">
		<div class="large-12 columns">&nbsp;</div>
	   </div>
	   <div class="row">
		<%= render 'layouts/mobile'%>
		<div class="large-4 columns">
		    <input type="search" placeholder="Search...@,#">
		    <div class="section-container accordion" data-section="accordion">
			  <section>
			    <h6 class="title" data-section-title>
                  <a href="#"><img class="th radius profile profeed"src="images/default_profile.jpg"> 
				    <div class="small-9 columns">
					  <div class="row">
					    <span class="small-10 columns feed">Section 1</span>
					    <span class="small-1 columns right feed"> 3d </span>
					  </div>
					</div>
					<div class="small-9 columns">
					  <div class="row">
					    <span class="small-12 columns feed">content and more and more content more and more and more</span>
					  </div>
					</div>
				    <span class="small-12 columns">link1 link2 link3</span>
				  </a>
				</h6>		
			    <div class="content" data-section-content>
			      <p>Content of section 1.</p>
			    </div>
			  </section>
			  <section>
			    <p class="title" data-section-title><a href="#"><img class="th radius" width="50" height="50"src="images/default_profile.jpg"> Section 2</a></p>
			    <div class="content" data-section-content>
			      <p>Content of section 2.</p>
			    </div>
			  </section>
			  <section>
			    <p class="title" data-section-title><a href="#"><img class="th radius" width="50" height="50"src="images/default_profile.jpg"> Section 3</a></p>
			    <div class="content" data-section-content>
			      <p>Content of section 1.</p>
			    </div>
			  </section>
			  <section>
			    <p class="title" data-section-title><a href="#"><img class="th radius" width="50" height="50"src="images/default_profile.jpg"> Section 4</a></p>
			    <div class="content" data-section-content>
			      <p>Content of section 2.</p>
			    </div>
			  </section>
			  <section>
			    <p class="title" data-section-title><a href="#"><img class="th radius" width="50" height="50"src="images/default_profile.jpg"> Section 5</a></p>
			    <div class="content" data-section-content>
			      <p>Content of section 1.</p>
			    </div>
			  </section>
			  <section>
			    <p class="title" data-section-title><a href="#"><img class="th radius" width="50" height="50"src="images/default_profile.jpg"> Section 6</a></p>
			    <div class="content" data-section-content>
			      <p>Content of section 2.</p>
			    </div>
			  </section>
			  <section>
			    <p class="title" data-section-title><a href="#"><img class="th radius" width="50" height="50"src="images/default_profile.jpg"> Section 7</a></p>
			    <div class="content" data-section-content>
			      <p>Content of section 1.</p>
			    </div>
			  </section>
			  <section>
			    <p class="title" data-section-title><a href="#"><img class="th radius" width="50" height="50"src="images/default_profile.jpg"> Section 8</a></p>
			    <div class="content" data-section-content>
			      <p>Content of section 2.</p>
			    </div>
			  </section>
			</div>
		</div>
		<div class="large-4 columns">...</div>
       </div> <!--! end of #row -->
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Aldershot" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="off-canvas-wrap">
	  <div class="inner-wrap">
		<nav class="tab-bar has-form has-dropdown" data-topbar> 
		  <section class="left-small">
		    <a class="left-off-canvas-toggle menu-icon" ><span></span></a>
		  </section>
		  <section class="middle tab-bar-section">
            <%= render 'layouts/navigation' %>
		  </section>
		  <section class="right-small">
		    <a class="right-off-canvas-toggle menu-icon" ><span></span></a>
		  </section>
		</nav> 
		<aside class="left-off-canvas-menu"> 
          <%= render 'layouts/left_canvas' %>
		</aside> 
		<aside class="right-off-canvas-menu"> 
          <%= render 'layouts/right_canvas' %>
		</aside> 
		<section class="main-section">
            <div class="small-12 small-centered columns">
	          &nbsp;
              <header>
		        <%= render 'layouts/messages' %>
		      </header>
	        </div> 
			<div class="small-8 large-4 small-centered columns panel callout">
				<%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => 'form-vertical' }) do |f| %>
				  <div class="row"> 
					 <div class="large-12 small-12 columns"> 
						 <%= f.input :email, :autofocus => true, :label => false, :placeholder => "user@example.com" %> 
					 </div> 
				   </div> 
				   <div class="row"> 
					   <div class="large-8 small-8 columns">
					     <%= f.input :password, :label => false, :placeholder => "********" %>
					   </div>
					   <div class="large-4 small-4 columns">
					     <%= f.button :submit, "Sign in", :class => 'button tiny radius' %>
					   </div>
				   </div>  
				   <div class="row"> 
					 <div class="large-6 columns"> 
					   <%= f.input :remember_me, :input_html => { :checked => true }, :as => :boolean, :label => "Remember me" if devise_mapping.rememberable? %>
					   <%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
					     <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
					   <% end -%>
					 </div> 
				   </div> 
				<% end %>
			</div> 
			<div class="small-8 large-4 small-centered columns panel callout">
				<div>
		          <h3>&nbsp;&nbsp;&nbsp;New here? Sign up</h3>
		        </div>
				<%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:class => 'form-vertical' }) do |f| %>
				  <div class="row"> 
					 <div class="large-12 small-12 columns"> 
						 <%= f.input :name, :autofocus => true, :label => false, :placeholder => "Full Name" %> 
					 </div> 
				   </div>
				  <div class="row"> 
					 <div class="large-12 small-12 columns"> 
						 <%= f.input :email, :required => true, :label => false, :placeholder => "Email Address" %> 
					 </div> 
				   </div> 
				   <div class="row"> 
					   <div class="large-8 small-8 columns">
					     <%= f.input :password, :label => false, :required=> true, :placeholder => "Password" %>
					   </div>
				   </div>  
				   <div class="row"> 
					   <div class="large-8 small-8 columns">
					     <%= f.input :password_confirmation, :label => false, :required=> true, :placeholder => "Password Confirmation" %>
					   </div>
				   </div>
				   <div class="row"> 
					   <div class="large-6 columns">
					     <%= f.button :submit, "Sign up", :class => 'button success tiny radius' %>
					   </div>
				   </div> 
				<% end %>				
			</div>
		</section> 
		  <a class="exit-off-canvas"></a> 
	  </div>
	</div>
    <%= javascript_include_tag "application" %>
  </body>
</html>